### ISSUE TITLE
Clarify Expo support in documentation

### ISSUE THREAD

**Issue by jackel119** [arabold/react-native-whirlwind#1]
From what I'm seeing browsing through the code this _seems_ like it should be perfectly compatible with Expo (managed workflow) projects. However, it would certainly be nice to have this explicitly stated in the documentation as this is the kind of library many newcomers to React Native (who are quite likely to be using Expo) would be looking for.

**Comment by arabold** [comment]
Thanks for pointing this out. Yes, the package is perfectly compatible with both Expo-managed and bare workflows. There are zero 3rd party dependencies and no native packages required. I'll see where in the documentation I'll add a note about this.

**Comment by arabold** [comment]
Fixed in 0678f705d155cf3b284772b241581d05cd1091a3
