### ISSUE TITLE
Negative margin/paddings don't exist

### ISSUE THREAD

**Issue by josmithua** [arabold/react-native-whirlwind#6]
According to the docs [here](https://arabold.github.io/react-native-whirlwind/getting-started/migration-guide#migrating-from-tailwind-css), there should be classes for negative margins/paddings, but there are none exported from the [spacing](https://github.com/arabold/react-native-whirlwind/blob/main/src/styles/spacing.ts) source

**Comment by arabold** [comment]
Hehe. I'll have one ready later today, when I got some spare time.
